api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #       entryPoint:
    #         to: websecure
  websecure:
    address: ":443"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/configs"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "webmaster@ditschers.de"
      storage: acme.json
      httpChallenge:
        entryPoint: web
