api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  api:
    address: ":8080"
  mqtt-tls:
    address: ":8883"
  dnsovertls:
    address: ":853"
  dns:
    address: ":53/tcp"
  udpdns:
    address: ":53/udp"
  ping:
   address: ":8082"
  ftp:
    address: ":21"
  ftp-passive-0:
    address: ":40000"
  ftp-passive-1:
    address: ":40001"
  ftp-passive-2:
    address: ":40002"
  ftp-passive-3:
    address: ":40003"
  ftp-passive-4:
    address: ":40004"
  ftp-passive-5:
    address: ":40005"
  ftp-passive-6:
    address: ":40006"
  ftp-passive-7:
    address: ":40007"
  ftp-passive-8:
    address: ":40008"
  ftp-passive-9:
    address: ":40009"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik
  file:
    directory: /configs

certificatesResolvers:
  letsencrypt:
    acme:
      email: webmaster@ditschers.de
      storage: acme/acme.json
      httpChallenge:
        entryPoint: web

log:
  filePath: /logs/traefik.log
  level: INFO
  maxAge: 7
accessLog:
  filePath: /logs/access.log

serversTransport:
  insecureSkipVerify: true

ping:
  entryPoint: ping

# metrics:
#   influxDB2:
#     address: https://influx.home.ditscher.me
#     token: $INFLUX_TOKEN
#     org: ditscher
#     bucket: testing
#     additionalLabels:
#       host: traefik.home.ditscher.me
