api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      middlewares:
        - secHeaders@file
  traefik:
    address: ":8080"
  # dnsovertls:
  #   address: ":853"
  # dns:
  #   address: ":53"
  # udpdns:
  #   address: ":53/udp"
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: traefik
  file:
    directory: /configs

certificatesResolvers:
  letsencrypt:
    acme:
      email: webmaster@ditschers.de
      storage: acme.json
      httpChallenge:
        entryPoint: web

log:
  filePath: /logs/traefik.log
  level: INFO
accessLog:
  filePath: "/logs/access.log"
