http:
  routers:
    catchall-secure:
      entrypoints:
        - websecure
      rule: HostRegexp(`.+\.new\.home\..+`)
      service: secure-forward-to-other-server
    catchall:
      entrypoints:
        - web
      rule: HostRegexp(`.+\.new\.home\..+`)
      service: forward-to-other-server


  services:
    secure-forward-to-other-server:
      loadBalancer:
        servers:
          - url: https://192.168.1.202
    forward-to-other-server:
      loadBalancer:
        servers:
          - url: http://192.168.1.202
