http:
  routers:
    zigbee2mqtt:
      entrypoints:
        - websecure
      rule: Host(`zigbee2mqtt.home.ditschers.de`) || Host(`zigbee2mqtt.home.ditscher.me`)
      tls:
        certresolver: letsencrypt
      service: zigbee2mqtt
      middlewares:
        - secure-headers@file

  services:
    zigbee2mqtt:
      loadBalancer:
        servers:
          - url: http://zigbee2mqtt.local:8080
            weight: 9999
          - url: http://192.168.1.46:8080
            weight: 1
