http:
  routers:
    nextcloud:
      entrypoints:
        - web
      rule: |
        Host(`cloud.ditschers.de`, `newcloud.ditschers.de`,
                `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`, `nextcloud.vps.ditschers.de`,
                `cloud.vps.ditscher.rocks`, `newcloud.vps.ditscher.rocks`, `nextcloud.vps.ditscher.rocks`)
      service: apache2
#      middlewares:
#        - https-redirect
#        - apache2-redirect

    nextcloud-secure:
      entrypoints:
        - websecure
      rule: |
        Host(`cloud.ditschers.de`, `newcloud.ditschers.de`,
                `cloud.vps.ditschers.de`, `newcloud.vps.ditschers.de`, `nextcloud.vps.ditschers.de`,
                `cloud.vps.ditscher.rocks`, `newcloud.vps.ditscher.rocks`, `nextcloud.vps.ditscher.rocks`)
#      tls:
#        certresolver: letsencrypt
      service: apache2
#      middlewares:
#        - secHeaders
#        - apache2-redirect
#  middlewares:
#    apache2-secure-redirect:
#      redirectscheme:
#        scheme: https
#        port: "1443"
#    apache2-redirect:
#      redirectscheme:
#        scheme: http
#        port: "180"
  services:
    apache2:
      loadBalancer:
        servers:
          - http://localhost:180
    apache2-secure:
      loadBalancer:
        servers:
          - https://localhost:1448


