# http:
#   routers:
#     unifi:
#       entrypoints:
#        - web
#       rule: Host(`unifi.m93.ditschers.de`)
#       service: apache2
#       middlewares:
#         - https-redirect


#     unifi-secure:
#       entrypoints:
#             websecure
#       rule: Host(`unify.m93.ditschers.de`)
#       tls:
#         certresolver: letsencrypt
#       service: unifi
#       middlewares:
#         - secHeaders

#
#   services:
#     unifi:
#       loadBalancer:
#         servers:
#           - localhost:1443
