---
http:
  routers:
    # homeserver:
    #   entrypoints:
    #     - web
    #   rule: HostRegexp(`^.*\.homeserver\..+`)
    #   service: homeserver
    #   middlewares:
    #     - https-redirect

    syncthing:
      entrypoints:
        - web
      rule: Host(`syncthing.homeserver.vps.ditschers.de`)
      service: homeserver
      middlewares:
        - https-redirect
    syncthing-secure:
      entrypoints:
        -  websecure
      rule: Host(`syncthing.homeserver.vps.ditschers.de`)
      tls:
        certresolver: letsencrypt
      service: syncthing
      middlewares:
#        - secHeaders
#        - syncthing-redirect

    unifi:
      entrypoints:
        - web
      rule: Host(`unifi.homeserver.vps.ditschers.de`)
      service: homeserver
      middlewares:
        - https-redirect
    unifi-secure:
      entrypoints:
        -  websecure
      rule: Host(`unifi.homeserver.vps.ditschers.de`)
      tls:
        certresolver: letsencrypt
      service: unifi
      middlewares:
        #- secHeaders
        - unifi-redirect

  middlewares:
    syncthing-redirect:
      redirectscheme:
        scheme: https
        port: "28384"
    unifi-redirect:
      redirectscheme:
        scheme: https
        port: "28443"

  services:
    homeserver:
      loadBalancer:
        servers:
          - url: "localhost"
    syncthing:
      loadBalancer:
        servers:
          - url: "https://127.0.0.1:28384"
    unifi:
      loadBalancer:
        servers:
          - url: "localhost:28443"

